"use client";
import { useEffect, useRef, useState } from "react";
import type { TxLineLiveSnapshot } from "@/lib/txline/types";
const DEFAULT_FIXTURE = "18237038";
export function LiveTxLine() {
  const [fixtureId, setFixtureId] = useState(DEFAULT_FIXTURE), [enabled, setEnabled] = useState(false), [snapshot, setSnapshot] = useState<TxLineLiveSnapshot | null>(null), [status, setStatus] = useState<"idle" | "connecting" | "live" | "fallback">("idle"), [message, setMessage] = useState("Connect a configured TxLINE feed to use real scores and odds.");
  const streams = useRef<EventSource[]>([]);
  useEffect(() => () => streams.current.forEach(stream => stream.close()), []);
  const refresh = async () => { try { const response = await fetch(`/api/txline/snapshot?fixtureId=${encodeURIComponent(fixtureId)}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setSnapshot(payload); setStatus("live"); } catch { setStatus("fallback"); } };
  const connect = async () => { streams.current.forEach(stream => stream.close()); streams.current = []; setStatus("connecting"); setMessage("Fetching authenticated TxLINE score and odds snapshots…"); try { const response = await fetch(`/api/txline/snapshot?fixtureId=${encodeURIComponent(fixtureId)}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "TxLINE snapshot failed"); setSnapshot(payload); setEnabled(true); setStatus("live"); setMessage("Live TxLINE snapshots and streams connected."); (["scores", "odds"] as const).forEach(feed => { const stream = new EventSource(`/api/txline/stream?feed=${feed}`); stream.onmessage = () => { setMessage(`Live ${feed} update received. Refreshing fixture snapshot…`); void refresh(); }; stream.onerror = () => setMessage(`${feed === "scores" ? "Scores" : "Odds"} stream reconnecting; latest snapshot remains visible.`); streams.current.push(stream); }); } catch (error) { setStatus("fallback"); setEnabled(false); setMessage(error instanceof Error ? `${error.message} Replay mode is still ready.` : "TxLINE unavailable. Replay mode is still ready."); } };
  const disconnect = () => { streams.current.forEach(stream => stream.close()); streams.current = []; setEnabled(false); setStatus("idle"); setMessage("Live feed disconnected. Replay mode remains available."); };
  return <section className="live-card"><div><p className="eyebrow">TXLINE REAL DATA</p><h2>Live fixture feed</h2><p>{message}</p></div><div className="live-controls"><label>Fixture ID<input value={fixtureId} onChange={event => setFixtureId(event.target.value.replace(/\D/g, ""))} inputMode="numeric" /></label>{enabled ? <><button className="secondary" onClick={() => void refresh()}>Refresh</button><button onClick={disconnect}>Disconnect</button></> : <button onClick={() => void connect()} disabled={!fixtureId || status === "connecting"}>{status === "connecting" ? "Connecting…" : "Connect TxLINE"}</button>}</div><div className="live-stats"><span className={`live-status ${status}`}>{status === "live" ? "● LIVE" : status === "fallback" ? "● REPLAY FALLBACK" : "● READY"}</span><span>Score <b>{snapshot?.score ?? "—"}</b></span><span>Game state <b>{snapshot?.gameState ?? "—"}</b></span><span>Fair probability <b>{snapshot?.fairProbability ? `${(snapshot.fairProbability * 100).toFixed(1)}%` : "—"}</b></span><span>Updated <b>{snapshot ? new Date(snapshot.updatedAt).toLocaleTimeString() : "—"}</b></span></div></section>;
}
