"use client";

import { useEffect, useRef, useState } from "react";
import { advanceReplayTick, createDemoState, finalReplayTick, replayIntervalMs } from "@/lib/varguard/engine";
import { replayScenarioById } from "@/lib/varguard/fixtures";
import { projectReplayNarrative, replayPhaseLabel } from "@/lib/varguard/narrative";
import { projectHedgeAdvisor } from "@/lib/varguard/advisor";
import { projectDecisionLog } from "@/lib/varguard/agent-log";
import { projectDemoTelemetryReceipt } from "@/lib/varguard/mock-ledger";
import type { AuditReceipt, DemoState, MarketState } from "@/lib/varguard/types";
import { LiveTxLine } from "./components/LiveTxLine";
import { PublicFootballSnapshot } from "./components/PublicFootballSnapshot";
import { MatchReplayPanel } from "./components/MatchReplayPanel";
import { MatchClipPanel } from "./components/MatchClipPanel";
import { DevnetDataControl } from "./components/DevnetDataControl";

const money = (value: number) => `${value.toFixed(2)} test units`;
const statusLabel = (value: string) => value.replaceAll("_", " ");

function QuoteBoard({ market }: { market: MarketState }) { return <div className="quotes">{market.quotes.map(quote => <div className={`quote ${quote.status.toLowerCase()}`} key={quote.id}><span>{quote.outcome} · {quote.side}</span><strong>{quote.price.toFixed(2)}</strong><span>{quote.size}u</span><em>{quote.status}</em></div>)}</div>; }
function ReceiptDrawer({ receipt, onClose }: { receipt: AuditReceipt; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onClick={onClose}><aside className="receipt" role="dialog" aria-modal="true" aria-label="Audit receipt" onClick={event => event.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="eyebrow">DEMO-VERIFIED AUDIT RECEIPT</p><h2>{receipt.id}</h2><dl><div><dt>Match clock</dt><dd>{receipt.matchClock}</dd></div><div><dt>Source event</dt><dd>{receipt.eventId}</dd></div><div><dt>Action</dt><dd>{statusLabel(receipt.action)}</dd></div><div><dt>Verification</dt><dd className="success">{receipt.verification}</dd></div></dl><p>{receipt.reason}</p></aside></div>; }

function MarketPanel({ market, protectedMarket, narrative, state }: { market: MarketState; protectedMarket?: boolean; narrative: ReturnType<typeof projectReplayNarrative>; state: DemoState }) {
  const avoided = Math.max(0, state.naive.loss - state.guard.loss);
  const fast = state.scenarioId === "fast-judge";
  const isFailure = !protectedMarket && market.loss > 0;
  const isProtected = protectedMarket && (state.guard.cancelledQuotes > 0 || state.guard.preventedFills > 0);
  const displayStatus = fast ? (protectedMarket ? (state.tick >= 20 ? "OPEN" : state.tick >= 19 ? "REOPENED" : state.tick >= 18 ? "REPRICING" : state.tick >= 6 ? "FROZEN" : "OPEN") : state.tick >= 7 ? "STILL OPEN" : "OPEN") : (protectedMarket ? statusLabel(market.status) : market.loss > 0 ? "STILL OPEN" : statusLabel(market.status));
  const explanation = protectedMarket ? "VARGuard paused trading before old prices could be exploited." : "The market kept old prices open after a match-changing incident.";
  return <section className={`market-panel ${protectedMarket ? "protected" : "naive"} ${isFailure ? "failed" : ""} ${isProtected ? "protected-active" : ""}`}><div className="panel-head"><div><p className="eyebrow">{protectedMarket ? "VARGuard" : "Naive Market"}</p><h2>{protectedMarket ? "PROTECTED" : isFailure ? "FAILED TO REACT" : "Naive Market"}</h2><p className="guard-note">{protectedMarket ? "Stops trading automatically during event risk" : "Leaves old prices open during event risk"}</p></div><span className="status">{displayStatus}</span></div><div className="stat-grid"><div><small>Status</small><b>{displayStatus}</b></div><div><small>What it does</small><b>{protectedMarket ? narrative.guardResponse : narrative.naiveResponse}</b></div><div><small>{protectedMarket ? "Bad trades stopped" : "Bad trades"}</small><b>{protectedMarket ? market.preventedFills : market.staleFills}</b></div><div><small>{protectedMarket ? "Saved" : "Loss"}</small><b className={protectedMarket ? "success" : "danger"}>{protectedMarket && avoided > 0 ? "+" : !protectedMarket && market.loss > 0 ? "−" : ""}{money(protectedMarket ? avoided : market.loss)}</b></div></div>{state.tick >= 6 && <p className="plain-explanation"><b>What happened:</b> {explanation}</p>}</section>;
}

function AdvancedDetails({ state, onReceipt, activationReady }: { state: DemoState; onReceipt: (receipt: AuditReceipt) => void; activationReady: boolean }) {
  const telemetry = projectDemoTelemetryReceipt(state);
  const avoided = Math.max(0, state.naive.loss - state.guard.loss);
  const latestAction = state.actions.at(-1);
  const latestReceipt = state.receipts.at(-1);
  return <><section className="mock-ledger" aria-label="Demo telemetry receipt"><div className="section-title"><div><p className="eyebrow">DEMO TELEMETRY RECEIPT · SOLANA DEVNET-STYLE FORMAT</p><h2>Latest policy receipt</h2></div><span>DISPLAY ONLY · NOT SUBMITTED ON-CHAIN</span></div><div className="telemetry-summary"><span><small>Scenario</small><b>{state.fixture.label}</b></span><span><small>Current tick</small><b>{state.tick}</b></span><span><small>Current event</small><b>{telemetry.event.type}</b></span><span><small>Naive loss</small><b className="danger">{money(state.naive.loss)}</b></span><span><small>VARGuard avoided</small><b className="success">{money(avoided)}</b></span><span><small>Latest action</small><b>{latestAction ? statusLabel(latestAction.type) : "Monitoring"}</b></span><span><small>Latest receipt</small><b>{latestReceipt?.id ?? "No receipt yet"}</b></span></div><pre>{JSON.stringify(telemetry, null, 2)}</pre><p className="telemetry-disclaimer">Demo receipt format. The hackathon replay does not submit real transactions, custody funds, or execute trades.</p></section><PublicFootballSnapshot /><div className="comparison"><section className="log-card"><p className="eyebrow">QUOTE BOARD</p><h2>Naive market quotes</h2><QuoteBoard market={state.naive} /></section><section className="log-card"><p className="eyebrow">QUOTE BOARD</p><h2>VARGuard quotes</h2><QuoteBoard market={state.guard} /></section></div><section className="receipts"><div className="section-title"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Decision receipts</h2></div><span>{state.receipts.length} verified</span></div><div className="receipt-list">{state.receipts.length === 0 ? <p className="empty">Receipts appear after a risk action.</p> : state.receipts.map(receipt => <button key={receipt.id} onClick={() => onReceipt(receipt)}><span className="verified">✓ VERIFIED</span><b>{receipt.id}</b><span>{statusLabel(receipt.action)}</span><i>View →</i></button>)}</div></section><LiveTxLine activationReady={activationReady} /></>;
}

function HedgeAdvisor({ state }: { state: DemoState }) {
  const brief = projectHedgeAdvisor(state);
  if (!brief) return null;
  return <section className="log-card advisor-card"><div className="section-title"><div><p className="eyebrow">AI HEDGE ADVISOR · {brief.mode.replaceAll("_", " ")}</p><h2>What a human operator could do next</h2></div><span className="success">{brief.confidence} confidence</span></div><p><b>Risk detected:</b> {brief.riskDetected}</p><p><b>Exposure concern:</b> {brief.exposureConcern}</p><ol className="advisor-list">{brief.recommendedMoves.map((move, index) => <li key={move.type}><time>{index + 1}</time><b>{move.label}</b></li>)}</ol><p className="empty">{brief.reason}</p><p className="advisor-disclaimer">AI explains recommended hedge moves after the deterministic engine acts. It does not execute trades or control market state.</p></section>;
}

export default function Home() {
  const [state, setState] = useState<DemoState>(() => createDemoState());
  const [selectedReceipt, setSelectedReceipt] = useState<AuditReceipt | null>(null), [advancedOpen, setAdvancedOpen] = useState(false);
  const [txLineActive, setTxLineActive] = useState(false);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const stateRef = useRef(state);
  useEffect(() => { stateRef.current = state; }, [state]);
  const clearReplayInterval = () => { if (intervalRef.current) { clearInterval(intervalRef.current); intervalRef.current = null; } };
  const runInterval = (speed: number) => { clearReplayInterval(); intervalRef.current = setInterval(() => { const next = advanceReplayTick(stateRef.current); stateRef.current = { ...next, running: next.tick < finalReplayTick(next), speed }; setState(stateRef.current); if (next.tick >= finalReplayTick(next)) clearReplayInterval(); }, replayIntervalMs(speed)); };
  useEffect(() => () => clearReplayInterval(), []);
  const start = () => { const next = stateRef.current.tick === 0 || stateRef.current.tick >= finalReplayTick(stateRef.current) ? { ...createDemoState(stateRef.current.fixture), running: true, speed: stateRef.current.speed } : { ...stateRef.current, running: true }; clearReplayInterval(); setSelectedReceipt(null); stateRef.current = next; setState(next); runInterval(next.speed); };
  const pause = () => { clearReplayInterval(); const next = { ...stateRef.current, running: false }; stateRef.current = next; setState(next); };
  const reset = () => { clearReplayInterval(); setSelectedReceipt(null); const next = createDemoState(stateRef.current.fixture); stateRef.current = next; setState(next); };
  const setSpeed = (speed: number) => { const next = { ...stateRef.current, speed }; stateRef.current = next; setState(next); if (next.running) runInterval(speed); };
  const changeScenario = (scenarioId: DemoState["scenarioId"]) => { clearReplayInterval(); setSelectedReceipt(null); const next = createDemoState(replayScenarioById(scenarioId)); stateRef.current = next; setState(next); };
  const finalTick = finalReplayTick(state), narrative = projectReplayNarrative(state), decisionLog = projectDecisionLog(state), progress = state.tick / finalTick * 100;
  return <main><nav><div className="brand"><span>V</span><strong>VARGuard</strong><p>Live market risk control</p></div><span className="demo-pill">SIMULATED · NO REAL MONEY</span><DevnetDataControl onActivationChange={setTxLineActive} /></nav>
    <section className="intro"><p className="eyebrow">{state.scenarioId === "full-incident" ? "FULL SYNTHETIC INCIDENT REPLAY · VIDEO AND STATE SYNCHRONIZED" : "INTERNATIONAL TOURNAMENT REPLAY · TEST UNITS ONLY"}</p><h1>A goal happens. Naive markets lose money. VARGuard stops the loss.</h1><p>Replay one match-changing event and see how VARGuard prevents stale-quote losses.</p><div className="scenario-picker" aria-label="Replay mode"><button className={state.scenarioId === "full-incident" ? "selected" : ""} onClick={() => changeScenario("full-incident")} disabled={state.running}>Full incident replay <small>complete</small></button><button className={state.scenarioId === "fast-judge" ? "selected" : ""} onClick={() => changeScenario("fast-judge")} disabled={state.running}>Fast judge demo <small>20 sec</small></button></div><p className="scenario-helper">{state.fixture.helperText}</p><div className="controls"><button onClick={state.running ? pause : start}>{state.running ? "Pause" : "Start demo"}</button><button className="secondary" onClick={reset}>Reset</button><select aria-label="Replay speed" value={state.speed} onChange={event => setSpeed(Number(event.target.value))}><option value={1}>1×</option><option value={3}>3×</option><option value={5}>5×</option></select></div></section>
    <section className="replay-card event-banner"><div><p className="eyebrow">{state.fixture.label.toUpperCase()} · TICK {state.tick} / {finalTick}</p><h2>{narrative.bannerTitle}</h2><p className="lede">{narrative.bannerSubtitle}</p></div><div className="replay-metric"><small>{state.fixture.homeTeam.toUpperCase()} VS {state.fixture.awayTeam.toUpperCase()}</small><b>{state.score}</b><span>{replayPhaseLabel(state.phase)}</span></div><div className="progress"><i style={{ width: `${progress}%` }} /></div></section>
    <section className="incident-replay" aria-label="Match incident replay"><div className="incident-title"><p className="eyebrow">MATCH INCIDENT REPLAY</p><h2>See the event before the market reaction</h2></div><div className="incident-grid"><MatchClipPanel tick={state.tick} isRunning={state.running} speed={state.speed} finalTick={finalTick} videoDurationSeconds={state.fixture.videoDurationSeconds} accelerated={state.scenarioId === "fast-judge"} /><MatchReplayPanel state={state} /></div></section>
    <section className="comparison"><MarketPanel market={state.naive} narrative={narrative} state={state} /><MarketPanel market={state.guard} protectedMarket narrative={narrative} state={state} /></section>
    <section className="receipts result-strip"><p className="eyebrow">DEMO RESULT</p><h2>{narrative.result}</h2></section>
    <section className="bottom-grid"><div className="log-card"><div className="section-title"><div><p className="eyebrow">MATCH STORY</p><h2>{state.fixture.homeTeam} vs {state.fixture.awayTeam}</h2></div><span>{state.fixture.description}</span></div><p className="fixture-context"><b>Halftime: {state.fixture.homeTeam} {state.fixture.halftimeScore} {state.fixture.awayTeam}</b> · Egypt-win probability {Math.round(state.fixture.initialFairProbability * 100)}% · Synthetic replay · test units only</p><ol>{narrative.steps.map(item => <li key={item.id}><time>Tick {item.tick}</time><b>{item.state === "complete" ? "✓ " : item.state === "active" ? "● " : "○ "}{item.title}</b><span>{item.detail}</span></li>)}</ol></div><div className="log-card"><div className="section-title"><div><p className="eyebrow">AUTONOMOUS POLICY LOG · DETERMINISTIC</p><h2>VARGuard actions</h2></div><span>{decisionLog.length} entries</span></div>{decisionLog.length === 0 ? <p className="empty">Policy telemetry will appear as the replay advances.</p> : <ol className="terminal-log">{decisionLog.slice().reverse().map(entry => <li key={entry.id} className={entry.level.toLowerCase()}><time>T+{entry.tick.toString().padStart(2, "0")}</time><b>{entry.level}</b><span>{entry.message}</span></li>)}</ol>}</div></section>
    <HedgeAdvisor state={state} />
    <details className="receipts" open={advancedOpen} onToggle={event => setAdvancedOpen(event.currentTarget.open)}><summary>Advanced details <span>quotes · receipts · public context · TxLINE</span></summary>{advancedOpen && <AdvancedDetails state={state} onReceipt={setSelectedReceipt} activationReady={txLineActive} />}</details>
    <footer className="app-footer">VARGuard uses deterministic policies and simulated test units. It does not execute trades, custody funds, or accept deposits.</footer>{selectedReceipt && <ReceiptDrawer receipt={selectedReceipt} onClose={() => setSelectedReceipt(null)} />}</main>;
}
