import type { TxLineConfig, TxLineFeed, TxLineLiveSnapshot } from "./types";
let guestJwt: string | undefined;
export function getTxLineConfig(): TxLineConfig | null { const apiToken = process.env.TXLINE_API_TOKEN; return apiToken ? { origin: process.env.TXLINE_API_ORIGIN ?? "https://txline.txodds.com", jwt: process.env.TXLINE_JWT, apiToken } : null; }
async function resolveJwt(config: TxLineConfig, renew = false) { if (!renew && (config.jwt ?? guestJwt)) return config.jwt ?? guestJwt!; const response = await fetch(`${config.origin}/auth/guest/start`, { method: "POST", cache: "no-store" }); if (!response.ok) throw new Error(`TxLINE guest authentication failed: ${response.status}`); const data = await response.json() as { token?: string }; if (!data.token) throw new Error("TxLINE guest authentication did not return a token"); guestJwt = data.token; return guestJwt; }
export async function txLineHeaders(config: TxLineConfig, renew = false): Promise<HeadersInit> { return { Authorization: `Bearer ${await resolveJwt(config, renew)}`, "X-Api-Token": config.apiToken, Accept: "application/json" }; }
const rec = (x: unknown): Record<string, unknown> => x && typeof x === "object" ? x as Record<string, unknown> : {};
const last = (x: unknown) => Array.isArray(x) ? rec(x.at(-1)) : rec(x);
const num = (x: unknown) => { const value = typeof x === "number" ? x : Number(x); return Number.isFinite(value) ? value : undefined; };
export function normalizeTxLineSnapshot(fixtureId: string, scores: unknown, odds: unknown): TxLineLiveSnapshot { const score = last(scores), price = last(odds); const home = num(score.HomeScore ?? score.homeScore ?? score.Participant1Score), away = num(score.AwayScore ?? score.awayScore ?? score.Participant2Score); const direct = num(price.FairProbability ?? price.fairProbability ?? price.Probability), decimal = num(price.DecimalOdds ?? price.decimalOdds ?? price.Odds); const probability = direct === undefined ? (decimal && decimal > 1 ? 1 / decimal : undefined) : direct > 1 ? direct / 100 : direct; return { fixtureId, score: home !== undefined && away !== undefined ? `${home}–${away}` : undefined, gameState: typeof (score.GameState ?? score.gameState) === "string" ? String(score.GameState ?? score.gameState) : undefined, fairProbability: probability, updatedAt: String(score.Ts ?? score.ts ?? price.Ts ?? price.ts ?? new Date().toISOString()), source: "TXLINE", raw: { scores, odds } }; }
export async function fetchTxLineSnapshot(fixtureId: string, configured?: TxLineConfig | null) { const config = configured ?? getTxLineConfig(); if (!config) throw new Error("TxLINE is not configured. Activate devnet data or set TXLINE_API_TOKEN on the server."); const request = async (renew = false) => Promise.all([fetch(`${config.origin}/api/scores/updates/${encodeURIComponent(fixtureId)}`, { headers: await txLineHeaders(config, renew), cache: "no-store" }), fetch(`${config.origin}/api/odds/snapshot/${encodeURIComponent(fixtureId)}`, { headers: await txLineHeaders(config, renew), cache: "no-store" })]); let [scores, odds] = await request(); if (scores.status === 401 || odds.status === 401) [scores, odds] = await request(true); if (!scores.ok || !odds.ok) throw new Error(`TxLINE snapshot failed: scores ${scores.status}, odds ${odds.status}`); return normalizeTxLineSnapshot(fixtureId, await scores.json(), await odds.json()); }
export function streamUrl(config: TxLineConfig, feed: TxLineFeed) { return `${config.origin}/api/${feed}/stream`; }
